services:
  alba:
    container_name: alba
    build:
      context: .
      dockerfile: Dockerfile
    image: alba
    restart: always
    ports:
      - 127.0.0.1:3001:3000
    networks:
      - alba_ui

networks:
  alba_ui:
    name: alba_ui
